# telegram_channels_to_parse = [
#     "jobs_in_it_remoute",
#     "odsjobs",
#     "it_vac",
#     "logic",
#     "myjobit",
#     "vakansii_it",
#     "itjobs_nocode",
#     "hiddengurus",
#     "JScript_jobs",
#     "ru_pythonjobs",
#     "runello_rus_python",
#     "runello_rus_c20",
#     "jvmjobs",
#     "mobile_jobs",
#     "GameDev_and_Tech_vacancy",
#     "Getitrussia",
#     "over100",
#     "fordev",
# ]
telegram_channels_to_parse = ["Vacanciesit"]
